### ISSUE TITLE
TypeError: key is not a function

### ISSUE THREAD

**Issue by JefSchraag** [cloudcrate/BlazorStorage#27]
When I invoke the `Key(i)` or `KeyAsync(i)` method, I get an exception:

```
TypeError: key is not a function
    at Object.Key (https://localhost:44329/_content/Cloudcrate.AspNetCore.Blazor.Browser.Storage/Storage.js:21:24)
    at Object.invokeJSFromDotNet (https://localhost:44329/_framework/blazor.webassembly.js:1:9737)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44329/_framework/wasm/dotnet.3.2.0.js:1:171433)
    at do_icall (<anonymous>:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (<anonymous>:wasm-function[1896]:0x50b6a)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x2588e)
    at interp_runtime_invoke (<anonymous>:wasm-function[5655]:0xf7391)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5109]:0xddb3d)
    at do_runtime_invoke (<anonymous>:wasm-function[1410]:0x3ba85)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[418]:0xcfdb)
```   
I checked in the debugger and and found that the `key` was indeed not a function but a string with the value `"instantiateWasm"`

**Comment by chris1411** [comment]
Same issue here. Any updates on this?
